import ImagoSymbol from '@/components/icons/imago-symbol';
import Link from 'next/link';
import React from 'react'
import ReactMarkdown from "react-markdown"

const submissionGuidelinesContent = [
    {
        title: "General Overview",
        content:
            "These Submission Guidelines govern any content you submit to Imago platforms, including app uploads, code contributions, AI prompts, feedback, community posts, and file submissions.\n\nBy submitting content, you confirm that you have the rights to share it and that it complies with these guidelines."
    },
    {
        title: "Prohibited Content",
        content:
            "You must not submit, post, or upload any content that:\n\n• Violates intellectual property rights (e.g., pirated apps, unlicensed images)\n• Contains hate speech, violence, discrimination, or harassment\n• Promotes terrorism, self-harm, or illegal activities\n• Contains malware, viruses, or harmful scripts\n• Spams or scams users through misleading links or promotional abuse\n\nWe reserve the right to reject or remove any content that breaches these rules."
    },
    {
        title: "Intellectual Property and Licensing",
        content:
            "By submitting content, you retain full ownership but grant Imago a limited, non-exclusive license to host, review, distribute, and showcase your submission across Imago services for operational or promotional purposes.\n\nYou must ensure your submission does not infringe upon any third-party rights and must include any required licenses, acknowledgments, or attributions."
    },
    {
        title: "App and Web Submissions",
        content:
            "For platforms like iStore or webStore, your submitted app or website must:\n\n• Be functional and not crash on launch\n• Clearly explain its purpose in the description\n• Not collect or share personal data without consent\n• Avoid copying the interface or features of other apps\n\nWe may conduct security reviews or require additional permissions for APIs or sensitive functionality."
    },
    {
        title: "Use of AI Features",
        content:
            "Any content submitted through or generated by Imago Intelligence must:\n\n• Be respectful and non-abusive toward the system or other users\n• Avoid prompt injections or attempts to manipulate AI output\n• Not include personally identifiable information unless required and secured\n\nWe may monitor AI prompts for abuse and retain anonymized logs to improve safety."
    },
    {
        title: "Moderation and Review Process",
        content:
            "All submissions are subject to manual or automated review.\n\nContent may be rejected, flagged, or delayed if it:\n\n• Violates our technical or ethical guidelines\n• Appears unsafe, plagiarized, or inappropriate\n• Contains broken links, inaccessible media, or misleading metadata\n\nYou will be notified via email or dashboard alerts if your submission requires changes."
    },
    {
        title: "Updates and Re-submissions",
        content:
            "If your content is updated (e.g., app version, title changes, or new assets), it must comply with the latest version of these guidelines.\n\nPreviously approved submissions may be reviewed again if we receive complaints or if policy changes."
    },
    {
        title: "Violations and Consequences",
        content:
            "Violations of these guidelines may result in:\n\n• Temporary or permanent removal of content\n• Suspension of your developer account\n• Legal action for serious or repeated offenses\n\nWe may also report unlawful content to appropriate authorities if required by law."
    },
    {
        title: "Contact and Appeals",
        content:
            "If you believe your content was removed or rejected unfairly, you may appeal the decision by contacting legal@imagollc.in with supporting details.\n\nWe will review your appeal and respond within 5–10 business days."
    }
];



function SubmissionPage() {
    return (
        <main className='w-full flex flex-col items-center justify-start gap-12 mb-32 pb-16 pt-5'>
            <section className='lg:max-w-[800px] w-[88%] flex flex-col lg:items-center items-baseline justify-center lg:text-center text-left gap-3 py-12 border-b border-border'>
                <h1 className='lg:text-5xl text-4xl font-bold'>Imago Submission Guidelines</h1>
                <p className='lg:text-xl text-lg'>General information about app or website submission</p>
            </section>

            <section className='lg:max-w-[800px] w-[88%] flex flex-col items-center justify-center gap-8'>
                {
                    submissionGuidelinesContent.map((item) => (
                        <div className='flex flex-col gap-2 text-left items-baseline text-lg' key={item.title}>
                            <h1 className='font-semibold text-2xl'>{item.title}</h1>
                            <ReactMarkdown>
                                {item.content}
                            </ReactMarkdown>
                        </div>
                    ))
                }


            </section>


            <section className='w-full flex items-center justify-center'>

                <div className='lg:w-[800px] w-[88%] rounded-lg lg:p-9 p-5 bg-muted flex flex-col gap-2'>
                    <label className='font-semibold text-muted-foreground mb-2'>Suggested Routes</label>
                    <div className='flex items-center gap-1.5 text-theme group'>
                        <ImagoSymbol name='doc_text' className='' />
                        <Link href={'/policy/terms'} className='group-hover:underline'>Explore Terms of Service</Link>
                    </div>
                    <div className='flex items-center gap-1.5 text-theme group'>
                        <ImagoSymbol name='doc_text' className='' />
                        <Link href={'/policy/developer'} className='group-hover:underline'>Learn about Our Developer Agreement</Link>
                    </div>
                </div>
            </section>
        </main>
    )
}

export default SubmissionPage