'use client'

import React, { useRef } from 'react'
import ImagoHero from '../../public/assets/home/imago-hero.webp'
import ImagoHeroSm from '../../public/assets/home/imago-hero-sm.webp'
import DeviceDesktopMockupSm from '../../public/assets/home/device-desktop-mockup-sm.webp'
import DeviceDesktopMockup from '../../public/assets/home/device-desktop-mockup.webp'
import AppsFloat from '../../public/assets/home/apps-float.webp'
import WebDesignTools from '../../public/assets/home/web-design-tools.webp'
import AiModels from '../../public/assets/home/ai-models.webp'
import ImagoOneGradient from '../../public/assets/home/imago-one-gradient.webp'
import ICreator from '../../public/assets/home/icreator.webp'
import Image, { type StaticImageData } from 'next/image'
import Link from 'next/link'
import { cva, type VariantProps } from 'class-variance-authority'
import { Slot } from '@radix-ui/react-slot'
import { cn } from '@/lib/utils'
import { TextEffect } from '@/components/motion-primitives/text-effect'
import { HyperRealistic, HyperRealisticLg, MedievalLg, Landscape, LandscapeLg, PastelArt, PastelArtLg, Robot } from '../../public/assets/home/carousel'
import ImagoSymbol from '@/components/icons/imago-symbol'
import { Marquee } from '@/components/magicui/marquee'
import { useIsMobile } from '@/hooks/use-mobile'
import ImagoIcon from '@/components/icons/imago-icon'


const buttonVariants = cva(
  "inline-flex items-center cursor-pointer justify-center text-body gap-2 md:text-[14px] font-normal whitespace-nowrap rounded-md transition-all disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 shrink-0 [&_svg]:shrink-0 outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
  {
    variants: {
      variant: {
        default:
          "bg-primary text-primary-foreground shadow-xs hover:bg-primary/90",
        destructive:
          "bg-destructive text-white shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
        outline:
          "border bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80",
        ghost:
          "hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
        link: "text-primary underline-offset-4 hover:underline",
        imago: "rounded-full hover:bg-[#007AFF] bg-[#0077ed] text-white",
        imagoOutline: "rounded-full bg-transparent text-[#007AFF] ring ring-[#007AFF] hover:bg-[#007AFF] hover:text-white",
      },
      size: {
        default: "md:h-9 h-9 md:px-4 px-4 py-1 has-[>svg]:px-3",
        sm: "h-8 rounded-md gap-1.5 px-3 has-[>svg]:px-2.5",
        lg: "h-10 rounded-md px-6 has-[>svg]:px-4",
        icon: "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & {
    asChild?: boolean
  }) {
  const Comp = asChild ? Slot : "button"

  return (
    <Comp
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}


const verticalImages: Image[] = [
  {
    title: "RealView",
    desc: "Ultra-detailed, lifelike AI creations.",
    url: HyperRealistic
  },
  {
    title: "EarthScape",
    desc: "Scenic nature views generated by AI.",
    url: Landscape
  },
  {
    title: "PastelTone",
    desc: "AI visuals with soft pastel tones.",
    url: PastelArt
  },
  {
    title: "NeuroBot",
    desc: "Futuristic robot concepts by AI.",
    url: Robot
  },
];

const horizontalImages: Image[] = [
  {
    title: "RealView Wide",
    desc: "Lifelike AI visuals in wide format.",
    url: HyperRealisticLg
  },
  {
    title: "EarthScape Wide",
    desc: "Wide-angle AI-generated landscapes.",
    url: LandscapeLg
  },
  {
    title: "PastelTone Wide",
    desc: "Creative pastel visuals in landscape view.",
    url: PastelArtLg
  },
  {
    title: "Hollow Era",
    desc: "Dark, moody medieval scenes by AI.",
    url: MedievalLg
  },
];





const IntelligencePage = () => {
  const isMobile = useIsMobile()

  return (
    <main className="w-full min-h-screen bg-white flex flex-col items-center justify-start gap-4">
      {/* <section className="w-full h-56 absolute top-12 bg-white/60 backdrop-blur-3xl">

      </section> */}
      <link rel="preload" as="image" href="../../public/assets/home/imago-hero.webp" />
      <section
        className="w-full sm:flex hidden flex-col items-center justify-center min-h-svh gap-3 relative bg-[#240043]"
      >

        <Image
          src={ImagoHero.src}
          alt="Imago hero"
          fill
          priority
          quality={100}
          className="object-contain object-center h-full"
        />
        <TextEffect preset='fade-in-blur' speedReveal={1.1} speedSegment={0.3} className='absolute bottom-1/6 md:bottom-1/12 text-white  text-lg text-center md:w-[80%] w-[88%]'>
          Welcome to imago llc. Here we craft intelligent digital solutions — Apps, Websites & AI That Work
          for You.
        </TextEffect>
      </section>
      <section
        className="w-full flex sm:hidden flex-col items-center justify-center min-h-svh gap-3 relative bg-[#240043]"
      >
        <Image
          src={ImagoHeroSm.src}
          alt="Imago hero"
          fill
          priority
          quality={100}
          className="object-contain object-center h-full"
        />
        <TextEffect preset='fade-in-blur' speedReveal={1.1} speedSegment={0.3} className='absolute bottom-1/6 md:bottom-1/12 text-white  text-lg text-center md:w-[80%] w-[88%]'>
          Welcome to imago llc. Here we craft intelligent digital solutions — Apps, Websites & AI That Work
          for You.
        </TextEffect>
      </section>

      <section className="w-full min-h-svh flex flex-col items-center justify-start md:pt-24 gap-2 bg-[#F2F2F7] py-12">
        <p className="md:text-5xl text-3xl font-semibold">Build. Launch. Evolve.</p>
        <p className="md:text-2xl text-xl md:w-[52%] w-[80%] text-center">At Imago, we specialize in crafting powerful digital experiences that push boundaries and drive results.</p>
        <Image src={DeviceDesktopMockupSm} alt="browser-mockup" style={{ width: 900, height: 'auto' }} priority className="mt-6 md:hidden" />
        <Image id="browser-mockup" src={DeviceDesktopMockup} alt="browser-mockup" style={{ width: 900, height: 'auto' }} className="mt-6 hidden md:flex" />
        <div className="flex items-center gap-4">
          <Button variant={'imago'} className=''>
            <Link href={'/apps'}>
              Visit our work
            </Link>
          </Button>
          <Button variant={'imagoOutline'}>
            <Link href={'/contact'}>
              Get a quote
            </Link>
          </Button>
        </div>
      </section>
      <section className="w-full min-h-svh flex flex-col items-center justify-center gap-2 py-12 bg-gradient-to-b from-[#D4EAF7] via-[#E6F1F7] to-[#FDFFFE]">
        <h1 className="md:text-5xl text-3xl font-semibold">App Development</h1>
        <p className="md:text-2xl text-xl md:w-[54%] w-[80%] text-center">We build fast, secure, and scalable mobile apps tailored to your unique needs — from idea to deployment.</p>
        <Image src={AppsFloat} alt="apps-float" style={{ width: 300, height: 'auto' }} />
        <div className="flex items-center gap-4">
          <Button variant={'imago'}>
            <Link href={'/apps'}>
              Visit iStore
            </Link>
          </Button>
          <Button variant={'imagoOutline'}>
            <Link href={'/contact'}>
              Build your app
            </Link>
          </Button>
        </div>
      </section>

      {/** Blocks Data Mapping */}
      <Blocks />

      {/**Carousel */}
      {isMobile ? <Carousel images={verticalImages} /> : <Carousel images={horizontalImages} />}


      <section className='bg-[#f5f5f7] text-black/60 mt-10 pt-7 w-full flex items-center justify-center'>
        <p className="text-xs text-muted-foreground leading-relaxed whitespace-pre-line w-[92%] md:max-w-[61rem] border-b border-border pb-8">
          ◊ Imago llc uses the SF Pro typeface to maintain a modern and accessible reading experience. SF Pro is a trademark of Apple Inc., registered in the U.S. and other countries.

          {"\n\n"}Our use of SF Pro is strictly for design and presentation purposes, with full respect for Apple&apos;s intellectual property. If you are an Apple representative or license holder and have questions or concerns about our usage, please feel free to <a href="/contact" className='underline'>contact us</a> — we are happy to discuss or make any adjustments needed.
        </p>
      </section>

    </main >
  )
}

export default IntelligencePage







const blocksData = [
  {
    id: 1,
    header: (
      <h1 className="text-3xl md:text-4xl font-semibold text-black pb-3">
        Web Development
      </h1>
    ),
    subText:
      "From sleek landing pages to full-scale platforms — we create responsive, SEO-friendly websites that impress and perform.",
    bgImage: <Image src={WebDesignTools} alt="block-bg" width={200} />,
    bgColor: "#F5F5F7",
    btnGroup: (
      <div className="flex items-center gap-4">
        <Button variant={'imago'}>
          <Link href={'/apps'}>
            Visit webStore
          </Link>
        </Button>
        <Button variant={'imagoOutline'}>
          <Link href={'/contact'}>
            Get a quote
          </Link>
        </Button>
      </div>
    ),
  },
  {
    id: 2,
    header: (
      <h1 className="text-3xl md:text-4xl font-semibold text-black pb-3">
        AI Integration
      </h1>
    ),
    subText:
      "We bring intelligence to your systems with cutting-edge AI. From smart search to chatbots — if it can think, we can build it.",
    bgImage: <Image src={AiModels} alt="block-bg" width={400} />,
    bgColor: "#F5F5F7",
    btnGroup: (
      <div className="flex flex-row gap-4">
        <Button variant={'imago'}>
          <Link href={'/intelligence'}>
            Chat with intelligence
          </Link>
        </Button>
      </div>
    ),
  },
  {
    id: 3,
    header: (
      <h1 className="text-3xl md:text-4xl font-semibold text-white pb-3">
        Imago One
      </h1>
    ),
    subText:
      "A simple, all-in-one subscription to unlock full access to the Imago ecosystem — including premium apps, tools, and AI features.",
    bgImage: <Image src={ImagoOneGradient} alt="block-bg" style={{ width: 400, height: 'auto' }} />,
    bgColor: "#000000",
    btnGroup: (
      <div className="flex flex-row gap-4">
        <Button variant={'imago'}>
          <Link href={'imago-one'}>
            Try imago one for free
          </Link>
        </Button>
      </div>
    ),
  },
  {
    id: 4,
    header: (
      <div className="flex items-center justify-center pb-3 gap-1">
        {/* <Image src={ImagoIcon as StaticImageData} alt='imago-icon' className='size-6' /> */}
        <ImagoIcon className='size-6' />
        <h1 className="text-3xl md:text-4xl font-semibold text-black text-center">
          Creator
        </h1>
      </div>
    ),
    subText:
      "Our dedicated platform for creators to publish their apps and websites directly to the Imago ecosystem.",
    bgImage: <Image src={ICreator} alt="block-bg" width={200} />,
    bgColor: "#F5F5F7",
    btnGroup: (
      <div className="flex flex-row gap-4 pt-10">
        <Button variant={'imago'}>
          <Link href={'https://icreator.vercel.app/'}>
            Visit iCreator
          </Link>
        </Button>
        <Button variant={'imagoOutline'}>
          <Link href={'https://icreator.vercel.app/documentation/app-submit'}>
            Read Docs
          </Link>
        </Button>
      </div>
    ),
  },
];


function Blocks() {
  return (
    <section className='md:w-[98%] w-full min-h-screen flex flex-row flex-wrap items-center justify-between gap-5'>
      {
        blocksData.map((block) => (
          <div
            key={block.id}
            style={{
              backgroundColor: block.bgColor,
            }}
            className={`md:w-[49%] shrink-0 relative w-full md:h-screen max-h-[700px]  flex flex-col items-center justify-center md:pt-12 py-16 gap-2`}
          >
            {block.header}
            <p
              className={`md:text-xl text-lg text-center px-6 md:px-16 ${block.bgColor === "#000000" ? "text-white" : "text-black"
                }`}
            >
              {block.subText}
            </p>
            {block.bgImage}
            {block.btnGroup}
          </div>
        ))
      }
    </section>
  )
}

type Image = {
  title: string;
  desc: string;
  url: StaticImageData;
}

interface CarouselProps {
  images: Image[]
}

function Carousel({ images }: CarouselProps) {
  const isMobile = useIsMobile()

  return (
    <div className='w-full md:h-[calc(100vh-200px)] h-[calc(100vh-400px)] overflow-y-clip flex items-center gap-5 relative'>

      <Marquee pauseOnHover className='[--duration:20s]'>
        {
          images.map((image, idx) => (
            <Link href={'/community'} key={idx} className='flex flex-col items-center justify-center gap-2 relative h-[30rem] md:h-[20rem]'>
              <Image src={image.url} alt={image.title} className={cn('h-full object-cover', isMobile ? 'w-[280px]' : 'w-fit')} width={280} height={400} />
              <div className='absolute bg-radial from-transparent to-black/70 w-full text-white flex flex-col h-full py-12 bottom-0 items-center justify-between gap-1'>
                <div className={`flex items-center gap-1 $`}>
                  <ImagoIcon className='size-3' />
                  <h1>Community+</h1>
                </div>
                <div className='flex flex-col items-center justify-center'>
                  <h1 className='text-xl font-semibold'>{image.title}</h1>
                  <p className=' text-center text-sm max-w-[75%] text-body'>{image.desc}</p>
                  <Button variant={'imago'} className='bg-black hover:bg-black/95 mt-1.5 inline-flex items-center gap-0.5'>
                    Create yours
                    <ImagoSymbol name='arrow_up_right' fontSize='18px' />
                  </Button>
                </div>
              </div>
            </Link>
          ))
        }
      </Marquee>

      {/* <button onClick={showNextImage} className='h-full w-12 flex items-center justify-center absolute right-0 bg-black/20'>
        <ImagoSymbol name='chevron_right' />
      </button>
      <button onClick={showPrevImage} className='h-full w-12 flex items-center justify-center absolute left-0 bg-black/20'>
        <ImagoSymbol name='chevron_left' />
      </button> */}
    </div>
  )
}
